"""
auth_routes.py
----------------
API endpoints for authentication:

    POST /auth/register     -> create a new user
    POST /auth/login        -> verify credentials, return a JWT
    GET  /auth/me            -> protected: return the logged-in user's info
    GET  /auth/admin-check   -> protected + role-restricted demo route
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import User
from app.schemas import UserRegister, UserLogin, UserOut, Token
from app.auth import (
    hash_password,
    verify_password,
    create_access_token,
    get_current_user,
    require_role,
)

router = APIRouter(prefix="/auth", tags=["Authentication"])


@router.post("/register", response_model=Token, status_code=status.HTTP_201_CREATED)
def register(user_in: UserRegister, db: Session = Depends(get_db)):
    # Prevent duplicate accounts on the same email
    existing_user = db.query(User).filter(User.email == user_in.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email is already registered. Please sign in instead.",
        )

    new_user = User(
        name=user_in.full_name,
        email=user_in.email,
        password_hash=hash_password(user_in.password),
        role=user_in.role.value,
    )

    db.add(new_user)
    db.commit()
    db.refresh(new_user)  # loads id/created_at generated by PostgreSQL

    # Generate access_token so user is logged in immediately upon registration
    access_token = create_access_token(new_user)
    return Token(access_token=access_token)


@router.post("/login", response_model=Token)
def login(credentials: UserLogin, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.email == credentials.email).first()

    # Deliberately vague error message: don't reveal whether the email exists
    if not user or not verify_password(credentials.password, user.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
        )

    access_token = create_access_token(user)
    return Token(access_token=access_token)


from fastapi.security import OAuth2PasswordRequestForm

@router.post("/token", response_model=Token, summary="OAuth2 compatible token login for Swagger UI")
def login_for_access_token(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db),
):
    """Allows logging in directly from Swagger UI Authorize dialog (username = email)."""
    user = db.query(User).filter(User.email == form_data.username).first()
    if not user or not verify_password(form_data.password, user.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
        )

    access_token = create_access_token(user)
    return Token(access_token=access_token)



@router.get("/me", response_model=UserOut)
def read_current_user(current_user: User = Depends(get_current_user)):
    """Any authenticated user can call this to see their own profile."""
    return current_user


@router.get("/admin-check")
def admin_only_route(current_user: User = Depends(require_role("administrator"))):
    """
    Demo route proving RBAC works.
    Only users with role='administrator' can reach this point.
    """
    return {"message": f"Welcome, administrator {current_user.name}"}